name: "Deploy to Nuget"

on:
 push:
  branches:
   - 'main'

env:
 NuGetDirectory: ${{ github.workspace }}/nuget
 NuGetSource: "https://api.nuget.org/v3/index.json"

jobs:
 deploy:
  name: Deploy
  runs-on: windows-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Install node
    uses: actions/setup-node@v4
    with:
     node-version: 22.7.0

  - name: Install npm packages
    run: npm install

  - name: Build js/css
    run: npm run build:Release

  - name: Install dotnet
    uses: actions/setup-dotnet@v4
    with:
     global-json-file: global.json

  - name: Restore tools
    run: dotnet tool restore

  - name: Install workloads
    run: dotnet workload install maui

  - name: Restore packages
    run: dotnet restore build/nuget-packages.proj

  - name: Build libs
    run: dotnet build build/nuget-packages.proj --no-restore -c Release

  - name: Pack libs
    run: dotnet pack build/nuget-packages.proj --no-restore --no-build -c Release --output ${{ env.NuGetDirectory }}

  - name: Push libs
    run: dotnet pushpackages --folder ${{ env.NuGetDirectory }} --source ${{ env.NuGetSource }} --api-key ${{ secrets.NugetAuthToken }}