name: "Deploy to Nuget"

on:
 push:
  branches:
   - 'main'

env:
 NuGetDirectory: ${{ github.workspace }}/nuget
 NuGetSource: "https://api.nuget.org/v3/index.json"

jobs:
 deploy:
  name: Deploy
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Install node
    uses: actions/setup-node@v4
    with:
     node-version: 22.7.0

  - name: Install npm packages
    run: npm install

  - name: Build js/css
    run: npm run build:Release

  - name: Install dotnet
    uses: actions/setup-dotnet@v4
    with:
     global-json-file: global.json

  - name: Install workloads
    run: dotnet workload install maui-windows maui-android maui-ios maui-maccatalyst

  - name: Restore packages
    run: dotnet restore build/packages.proj

  - name: Build libs
    run: dotnet build build/packages.proj --no-restore --configuration Release

  - name: Pack libs
    run: dotnet pack build/packages.proj --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.NuGetDirectory }}

  - name: Push libs
    run: dotnet nuget push ${{ env.NuGetDirectory }}\*nupkg -s ${{ env.NuGetSource }} -k ${{ secrets.NugetAuthToken }}